// lib/foodDatabase.ts
// Kalorix — Bibliothèque Cuisines du Monde
// ~116 plats · calories pour portion standard · trilingue FR/EN/ES

export interface LocalFood {
  id: string;
  cuisine: "daily" | "us" | "ca" | "ma" | "fr" | "it" | "mx" | "jp";
  name: { fr: string; en: string; es: string };
  calories: number;
  portion: { fr: string; en: string; es: string };
  portionGrams: number;
  proteines?: number;  // g
  glucides?: number;   // g
  lipides?: number;    // g
}

export const foodDatabase: LocalFood[] = [

  // ────────────────────────────────────────────
  // ⭐ QUOTIDIEN (~36 aliments)
  // ────────────────────────────────────────────

  {
    id: "daily-01",
    cuisine: "daily",
    name: { fr: "Café noir (sans sucre)", en: "Black Coffee (no sugar)", es: "Café negro (sin azúcar)" },
    calories: 5,
    portion: { fr: "1 tasse (240ml)", en: "1 cup (240ml)", es: "1 taza (240ml)" },
    portionGrams: 240,
    proteines: 0, glucides: 1, lipides: 0,
  },
  {
    id: "daily-02",
    cuisine: "daily",
    name: { fr: "Café au lait", en: "Café au Lait", es: "Café con leche" },
    calories: 60,
    portion: { fr: "1 tasse (240ml)", en: "1 cup (240ml)", es: "1 taza (240ml)" },
    portionGrams: 240,
    proteines: 3, glucides: 6, lipides: 2,
  },
  {
    id: "daily-03",
    cuisine: "daily",
    name: { fr: "Thé nature (sans sucre)", en: "Plain Tea (no sugar)", es: "Té solo (sin azúcar)" },
    calories: 2,
    portion: { fr: "1 tasse (240ml)", en: "1 cup (240ml)", es: "1 taza (240ml)" },
    portionGrams: 240,
    proteines: 0, glucides: 0, lipides: 0,
  },
  {
    id: "daily-04",
    cuisine: "daily",
    name: { fr: "Lait demi-écrémé", en: "Semi-skimmed Milk", es: "Leche semidesnatada" },
    calories: 110,
    portion: { fr: "1 verre (250ml)", en: "1 glass (250ml)", es: "1 vaso (250ml)" },
    portionGrams: 250,
    proteines: 8, glucides: 12, lipides: 4,
  },
  {
    id: "daily-05",
    cuisine: "daily",
    name: { fr: "Jus d'orange (pressé)", en: "Fresh Orange Juice", es: "Zumo de naranja natural" },
    calories: 110,
    portion: { fr: "1 verre (250ml)", en: "1 glass (250ml)", es: "1 vaso (250ml)" },
    portionGrams: 250,
    proteines: 2, glucides: 26, lipides: 0,
  },
  {
    id: "daily-06",
    cuisine: "daily",
    name: { fr: "Œuf à la coque", en: "Soft-boiled Egg", es: "Huevo pasado por agua" },
    calories: 70,
    portion: { fr: "1 œuf", en: "1 egg", es: "1 huevo" },
    portionGrams: 50,
    proteines: 6, glucides: 0, lipides: 5,
  },
  {
    id: "daily-07",
    cuisine: "daily",
    name: { fr: "Œufs brouillés (x2)", en: "Scrambled Eggs (x2)", es: "Huevos revueltos (x2)" },
    calories: 180,
    portion: { fr: "2 œufs", en: "2 eggs", es: "2 huevos" },
    portionGrams: 110,
    proteines: 12, glucides: 1, lipides: 14,
  },
  {
    id: "daily-08",
    cuisine: "daily",
    name: { fr: "Yaourt nature (125g)", en: "Plain Yogurt (125g)", es: "Yogur natural (125g)" },
    calories: 70,
    portion: { fr: "1 pot (125g)", en: "1 pot (125g)", es: "1 bote (125g)" },
    portionGrams: 125,
    proteines: 5, glucides: 8, lipides: 2,
  },
  {
    id: "daily-09",
    cuisine: "daily",
    name: { fr: "Yaourt grec (150g)", en: "Greek Yogurt (150g)", es: "Yogur griego (150g)" },
    calories: 130,
    portion: { fr: "1 pot (150g)", en: "1 pot (150g)", es: "1 bote (150g)" },
    portionGrams: 150,
    proteines: 12, glucides: 6, lipides: 6,
  },
  {
    id: "daily-10",
    cuisine: "daily",
    name: { fr: "Fromage blanc (100g)", en: "Fromage Blanc (100g)", es: "Queso blanco (100g)" },
    calories: 75,
    portion: { fr: "100g", en: "100g", es: "100g" },
    portionGrams: 100,
    proteines: 8, glucides: 5, lipides: 2,
  },
  {
    id: "daily-11",
    cuisine: "daily",
    name: { fr: "Camembert (30g)", en: "Camembert (30g)", es: "Camembert (30g)" },
    calories: 90,
    portion: { fr: "1 portion (30g)", en: "1 serving (30g)", es: "1 porción (30g)" },
    portionGrams: 30,
    proteines: 5, glucides: 0, lipides: 7,
  },
  {
    id: "daily-12",
    cuisine: "daily",
    name: { fr: "Fromage (emmental, 30g)", en: "Swiss Cheese (30g)", es: "Queso emmental (30g)" },
    calories: 115,
    portion: { fr: "1 tranche (30g)", en: "1 slice (30g)", es: "1 loncha (30g)" },
    portionGrams: 30,
    proteines: 8, glucides: 0, lipides: 9,
  },
  {
    id: "daily-13",
    cuisine: "daily",
    name: { fr: "Pain blanc (1 tranche)", en: "White Bread (1 slice)", es: "Pan blanco (1 rebanada)" },
    calories: 80,
    portion: { fr: "1 tranche (30g)", en: "1 slice (30g)", es: "1 rebanada (30g)" },
    portionGrams: 30,
    proteines: 3, glucides: 15, lipides: 1,
  },
  {
    id: "daily-14",
    cuisine: "daily",
    name: { fr: "Pain complet (1 tranche)", en: "Wholemeal Bread (1 slice)", es: "Pan integral (1 rebanada)" },
    calories: 70,
    portion: { fr: "1 tranche (30g)", en: "1 slice (30g)", es: "1 rebanada (30g)" },
    portionGrams: 30,
    proteines: 3, glucides: 12, lipides: 1,
  },
  {
    id: "daily-15",
    cuisine: "daily",
    name: { fr: "Flocons d'avoine (porridge)", en: "Oatmeal (porridge)", es: "Avena (porridge)" },
    calories: 190,
    portion: { fr: "1 bol (200g)", en: "1 bowl (200g)", es: "1 tazón (200g)" },
    portionGrams: 200,
    proteines: 6, glucides: 32, lipides: 4,
  },
  {
    id: "daily-16",
    cuisine: "daily",
    name: { fr: "Riz blanc cuit (150g)", en: "Cooked White Rice (150g)", es: "Arroz blanco cocido (150g)" },
    calories: 195,
    portion: { fr: "1 portion (150g)", en: "1 serving (150g)", es: "1 porción (150g)" },
    portionGrams: 150,
    proteines: 4, glucides: 43, lipides: 0,
  },
  {
    id: "daily-17",
    cuisine: "daily",
    name: { fr: "Pâtes cuites (200g)", en: "Cooked Pasta (200g)", es: "Pasta cocida (200g)" },
    calories: 260,
    portion: { fr: "1 assiette (200g)", en: "1 plate (200g)", es: "1 plato (200g)" },
    portionGrams: 200,
    proteines: 9, glucides: 52, lipides: 1,
  },
  {
    id: "daily-18",
    cuisine: "daily",
    name: { fr: "Banane", en: "Banana", es: "Plátano" },
    calories: 90,
    portion: { fr: "1 banane moyenne", en: "1 medium banana", es: "1 plátano mediano" },
    portionGrams: 100,
    proteines: 1, glucides: 23, lipides: 0,
  },
  {
    id: "daily-19",
    cuisine: "daily",
    name: { fr: "Pomme", en: "Apple", es: "Manzana" },
    calories: 80,
    portion: { fr: "1 pomme moyenne", en: "1 medium apple", es: "1 manzana mediana" },
    portionGrams: 150,
    proteines: 0, glucides: 21, lipides: 0,
  },
  {
    id: "daily-20",
    cuisine: "daily",
    name: { fr: "Orange", en: "Orange", es: "Naranja" },
    calories: 65,
    portion: { fr: "1 orange", en: "1 orange", es: "1 naranja" },
    portionGrams: 130,
    proteines: 1, glucides: 16, lipides: 0,
  },
  {
    id: "daily-21",
    cuisine: "daily",
    name: { fr: "Fraises (200g)", en: "Strawberries (200g)", es: "Fresas (200g)" },
    calories: 65,
    portion: { fr: "1 bol (200g)", en: "1 bowl (200g)", es: "1 tazón (200g)" },
    portionGrams: 200,
    proteines: 1, glucides: 15, lipides: 0,
  },
  {
    id: "daily-22",
    cuisine: "daily",
    name: { fr: "Dattes (x5)", en: "Dates (x5)", es: "Dátiles (x5)" },
    calories: 140,
    portion: { fr: "5 dattes", en: "5 dates", es: "5 dátiles" },
    portionGrams: 50,
    proteines: 1, glucides: 36, lipides: 0,
  },
  {
    id: "daily-23",
    cuisine: "daily",
    name: { fr: "Amandes (30g)", en: "Almonds (30g)", es: "Almendras (30g)" },
    calories: 175,
    portion: { fr: "1 poignée (30g)", en: "1 handful (30g)", es: "1 puñado (30g)" },
    portionGrams: 30,
    proteines: 6, glucides: 5, lipides: 15,
  },
  {
    id: "daily-24",
    cuisine: "daily",
    name: { fr: "Noix (30g)", en: "Walnuts (30g)", es: "Nueces (30g)" },
    calories: 195,
    portion: { fr: "1 poignée (30g)", en: "1 handful (30g)", es: "1 puñado (30g)" },
    portionGrams: 30,
    proteines: 5, glucides: 4, lipides: 19,
  },
  {
    id: "daily-25",
    cuisine: "daily",
    name: { fr: "Chocolat noir (30g)", en: "Dark Chocolate (30g)", es: "Chocolate negro (30g)" },
    calories: 165,
    portion: { fr: "3 carrés (30g)", en: "3 squares (30g)", es: "3 onzas (30g)" },
    portionGrams: 30,
    proteines: 2, glucides: 14, lipides: 11,
  },
  {
    id: "daily-26",
    cuisine: "daily",
    name: { fr: "Barre de céréales", en: "Cereal Bar", es: "Barrita de cereales" },
    calories: 130,
    portion: { fr: "1 barre (40g)", en: "1 bar (40g)", es: "1 barrita (40g)" },
    portionGrams: 40,
    proteines: 2, glucides: 22, lipides: 4,
  },
  {
    id: "daily-27",
    cuisine: "daily",
    name: { fr: "Beurre de cacahuète (1 c.s.)", en: "Peanut Butter (1 tbsp)", es: "Mantequilla de cacahuete (1 cda)" },
    calories: 95,
    portion: { fr: "1 cuillère à soupe (16g)", en: "1 tablespoon (16g)", es: "1 cucharada (16g)" },
    portionGrams: 16,
    proteines: 4, glucides: 3, lipides: 8,
  },
  {
    id: "daily-28",
    cuisine: "daily",
    name: { fr: "Avocat (demi)", en: "Avocado (half)", es: "Aguacate (medio)" },
    calories: 120,
    portion: { fr: "1/2 avocat", en: "1/2 avocado", es: "1/2 aguacate" },
    portionGrams: 100,
    proteines: 1, glucides: 6, lipides: 11,
  },
  {
    id: "daily-29",
    cuisine: "daily",
    name: { fr: "Poulet grillé (blanc, 150g)", en: "Grilled Chicken Breast (150g)", es: "Pechuga de pollo a la plancha (150g)" },
    calories: 230,
    portion: { fr: "1 blanc (150g)", en: "1 breast (150g)", es: "1 pechuga (150g)" },
    portionGrams: 150,
    proteines: 43, glucides: 0, lipides: 5,
  },
  {
    id: "daily-30",
    cuisine: "daily",
    name: { fr: "Thon en boîte (100g, égoutté)", en: "Canned Tuna (100g, drained)", es: "Atún en lata (100g, escurrido)" },
    calories: 120,
    portion: { fr: "1/2 boîte (100g)", en: "1/2 can (100g)", es: "1/2 lata (100g)" },
    portionGrams: 100,
    proteines: 26, glucides: 0, lipides: 1,
  },
  // — Nouveaux ajouts Session 15
  {
    id: "daily-31",
    cuisine: "daily",
    name: { fr: "Café (espresso / court)", en: "Espresso Coffee", es: "Café expreso" },
    calories: 50,
    portion: { fr: "1 tasse (100ml)", en: "1 cup (100ml)", es: "1 taza (100ml)" },
    portionGrams: 100,
    proteines: 1, glucides: 6, lipides: 1,
  },
  {
    id: "daily-32",
    cuisine: "daily",
    name: { fr: "Pur beurre de cacahuète (100g)", en: "Pure Peanut Butter (100g)", es: "Mantequilla de cacahuete pura (100g)" },
    calories: 590,
    portion: { fr: "100g", en: "100g", es: "100g" },
    portionGrams: 100,
    proteines: 25, glucides: 18, lipides: 50,
  },
  {
    id: "daily-33",
    cuisine: "daily",
    name: { fr: "Salade composée (200g)", en: "Mixed Salad (200g)", es: "Ensalada mixta (200g)" },
    calories: 200,
    portion: { fr: "1 assiette (200g)", en: "1 plate (200g)", es: "1 plato (200g)" },
    portionGrams: 200,
    proteines: 6, glucides: 14, lipides: 13,
  },
  {
    id: "daily-34",
    cuisine: "daily",
    name: { fr: "Filet de maquereaux au naturel (120g)", en: "Mackerel Fillet in Brine (120g)", es: "Filete de caballa al natural (120g)" },
    calories: 206,
    portion: { fr: "1 filet (120g)", en: "1 fillet (120g)", es: "1 filete (120g)" },
    portionGrams: 120,
    proteines: 22, glucides: 0, lipides: 13,
  },
  {
    id: "daily-35",
    cuisine: "daily",
    name: { fr: "Merguez grillées (x6, 330g)", en: "Grilled Merguez Sausages (x6)", es: "Merguez a la plancha (x6, 330g)" },
    calories: 291,
    portion: { fr: "6 pièces (330g)", en: "6 pieces (330g)", es: "6 piezas (330g)" },
    portionGrams: 330,
    proteines: 20, glucides: 2, lipides: 22,
  },

  // ────────────────────────────────────────────
  // 🇺🇸 AMÉRICAINE (~16 plats)
  // ────────────────────────────────────────────
  {
    id: "us-01",
    cuisine: "us",
    name: { fr: "Cheeseburger classique", en: "Classic Cheeseburger", es: "Hamburguesa con queso" },
    calories: 540,
    portion: { fr: "1 burger", en: "1 burger", es: "1 hamburguesa" },
    portionGrams: 200,
    proteines: 28, glucides: 42, lipides: 27,
  },
  {
    id: "us-02",
    cuisine: "us",
    name: { fr: "Hot-dog avec pain", en: "Hot Dog with Bun", es: "Hot Dog con pan" },
    calories: 290,
    portion: { fr: "1 hot-dog", en: "1 hot dog", es: "1 hot dog" },
    portionGrams: 130,
    proteines: 11, glucides: 28, lipides: 14,
  },
  {
    id: "us-03",
    cuisine: "us",
    name: { fr: "Mac & Cheese", en: "Mac & Cheese", es: "Mac & Cheese" },
    calories: 420,
    portion: { fr: "1 portion (250g)", en: "1 serving (250g)", es: "1 porción (250g)" },
    portionGrams: 250,
    proteines: 15, glucides: 55, lipides: 16,
  },
  {
    id: "us-04",
    cuisine: "us",
    name: { fr: "Pancakes (x3) avec sirop", en: "Pancakes (x3) with Syrup", es: "Panqueques (x3) con jarabe" },
    calories: 520,
    portion: { fr: "3 pancakes", en: "3 pancakes", es: "3 panqueques" },
    portionGrams: 220,
    proteines: 10, glucides: 85, lipides: 14,
  },
  {
    id: "us-05",
    cuisine: "us",
    name: { fr: "Caesar Salad", en: "Caesar Salad", es: "Ensalada César" },
    calories: 310,
    portion: { fr: "1 bol (300g)", en: "1 bowl (300g)", es: "1 tazón (300g)" },
    portionGrams: 300,
    proteines: 9, glucides: 18, lipides: 22,
  },
  {
    id: "us-06",
    cuisine: "us",
    name: { fr: "Buffalo Wings (6 pièces)", en: "Buffalo Wings (6 pieces)", es: "Alitas Buffalo (6 piezas)" },
    calories: 480,
    portion: { fr: "6 ailes", en: "6 wings", es: "6 alitas" },
    portionGrams: 240,
    proteines: 38, glucides: 8, lipides: 30,
  },
  {
    id: "us-07",
    cuisine: "us",
    name: { fr: "Grilled Cheese Sandwich", en: "Grilled Cheese Sandwich", es: "Sándwich de queso fundido" },
    calories: 390,
    portion: { fr: "1 sandwich", en: "1 sandwich", es: "1 sándwich" },
    portionGrams: 170,
    proteines: 16, glucides: 34, lipides: 20,
  },
  {
    id: "us-08",
    cuisine: "us",
    name: { fr: "BBQ Ribs", en: "BBQ Ribs", es: "Costillas BBQ" },
    calories: 620,
    portion: { fr: "1 portion (300g)", en: "1 serving (300g)", es: "1 porción (300g)" },
    portionGrams: 300,
    proteines: 45, glucides: 22, lipides: 36,
  },
  {
    id: "us-09",
    cuisine: "us",
    name: { fr: "Club Sandwich", en: "Club Sandwich", es: "Club Sándwich" },
    calories: 560,
    portion: { fr: "1 sandwich", en: "1 sandwich", es: "1 sándwich" },
    portionGrams: 280,
    proteines: 30, glucides: 45, lipides: 24,
  },
  {
    id: "us-10",
    cuisine: "us",
    name: { fr: "Cheesecake", en: "Cheesecake", es: "Cheesecake" },
    calories: 400,
    portion: { fr: "1 part (125g)", en: "1 slice (125g)", es: "1 rebanada (125g)" },
    portionGrams: 125,
    proteines: 7, glucides: 38, lipides: 24,
  },
  {
    id: "us-11",
    cuisine: "us",
    name: { fr: "Omelette 3 œufs", en: "3-Egg Omelette", es: "Tortilla de 3 huevos" },
    calories: 310,
    portion: { fr: "1 omelette", en: "1 omelette", es: "1 tortilla" },
    portionGrams: 200,
    proteines: 22, glucides: 2, lipides: 24,
  },
  {
    id: "us-12",
    cuisine: "us",
    name: { fr: "Soupe de tomates", en: "Tomato Soup", es: "Sopa de tomate" },
    calories: 180,
    portion: { fr: "1 bol (300ml)", en: "1 bowl (300ml)", es: "1 tazón (300ml)" },
    portionGrams: 300,
    proteines: 4, glucides: 26, lipides: 6,
  },
  {
    id: "us-13",
    cuisine: "us",
    name: { fr: "BLT Sandwich", en: "BLT Sandwich", es: "Sándwich BLT" },
    calories: 440,
    portion: { fr: "1 sandwich", en: "1 sandwich", es: "1 sándwich" },
    portionGrams: 220,
    proteines: 18, glucides: 38, lipides: 20,
  },
  {
    id: "us-14",
    cuisine: "us",
    name: { fr: "Cookies aux pépites de chocolat (x2)", en: "Chocolate Chip Cookies (x2)", es: "Galletas con chispas de chocolate (x2)" },
    calories: 280,
    portion: { fr: "2 cookies", en: "2 cookies", es: "2 galletas" },
    portionGrams: 80,
    proteines: 3, glucides: 38, lipides: 14,
  },
  {
    id: "us-15",
    cuisine: "us",
    name: { fr: "French Fries (portion moyenne)", en: "French Fries (medium)", es: "Papas fritas (mediana)" },
    calories: 365,
    portion: { fr: "1 portion moyenne", en: "1 medium serving", es: "1 porción mediana" },
    portionGrams: 170,
    proteines: 4, glucides: 48, lipides: 17,
  },
  // — Nouveau ajout Session 15
  {
    id: "us-16",
    cuisine: "us",
    name: { fr: "Maxi Cheese Burger", en: "Maxi Cheeseburger", es: "Maxi Hamburguesa con queso" },
    calories: 256,
    portion: { fr: "1 burger", en: "1 burger", es: "1 hamburguesa" },
    portionGrams: 130,
    proteines: 14, glucides: 24, lipides: 11,
  },

  // ────────────────────────────────────────────
  // 🇨🇦 CANADIENNE (~8 plats)
  // ────────────────────────────────────────────
  {
    id: "ca-01",
    cuisine: "ca",
    name: { fr: "Poutine classique", en: "Classic Poutine", es: "Poutine clásica" },
    calories: 740,
    portion: { fr: "1 portion (400g)", en: "1 serving (400g)", es: "1 porción (400g)" },
    portionGrams: 400,
    proteines: 22, glucides: 85, lipides: 36,
  },
  {
    id: "ca-02",
    cuisine: "ca",
    name: { fr: "Tourtière (part)", en: "Tourtière (slice)", es: "Tourtière (porción)" },
    calories: 430,
    portion: { fr: "1 part", en: "1 slice", es: "1 porción" },
    portionGrams: 200,
    proteines: 20, glucides: 32, lipides: 24,
  },
  {
    id: "ca-03",
    cuisine: "ca",
    name: { fr: "Sirop d'érable sur crêpes (x2)", en: "Maple Syrup Crêpes (x2)", es: "Crêpes con sirope de arce (x2)" },
    calories: 460,
    portion: { fr: "2 crêpes", en: "2 crêpes", es: "2 crêpes" },
    portionGrams: 200,
    proteines: 8, glucides: 72, lipides: 14,
  },
  {
    id: "ca-04",
    cuisine: "ca",
    name: { fr: "Soupe aux pois canadienne", en: "Canadian Pea Soup", es: "Sopa de guisantes canadiense" },
    calories: 220,
    portion: { fr: "1 bol (300ml)", en: "1 bowl (300ml)", es: "1 tazón (300ml)" },
    portionGrams: 300,
    proteines: 13, glucides: 32, lipides: 3,
  },
  {
    id: "ca-05",
    cuisine: "ca",
    name: { fr: "Butter Tart", en: "Butter Tart", es: "Tarta de mantequilla" },
    calories: 250,
    portion: { fr: "1 tarte", en: "1 tart", es: "1 tarta" },
    portionGrams: 75,
    proteines: 3, glucides: 36, lipides: 11,
  },
  {
    id: "ca-06",
    cuisine: "ca",
    name: { fr: "Bannique (pain autochtone)", en: "Bannock (Indigenous Bread)", es: "Bannock (pan indígena)" },
    calories: 310,
    portion: { fr: "1 part (100g)", en: "1 piece (100g)", es: "1 trozo (100g)" },
    portionGrams: 100,
    proteines: 7, glucides: 50, lipides: 9,
  },
  {
    id: "ca-07",
    cuisine: "ca",
    name: { fr: "Saumon de l'Atlantique grillé", en: "Grilled Atlantic Salmon", es: "Salmón atlántico a la plancha" },
    calories: 350,
    portion: { fr: "1 filet (200g)", en: "1 fillet (200g)", es: "1 filete (200g)" },
    portionGrams: 200,
    proteines: 40, glucides: 0, lipides: 20,
  },
  {
    id: "ca-08",
    cuisine: "ca",
    name: { fr: "Nanaimo Bar", en: "Nanaimo Bar", es: "Barra Nanaimo" },
    calories: 330,
    portion: { fr: "1 barre", en: "1 bar", es: "1 barra" },
    portionGrams: 90,
    proteines: 4, glucides: 38, lipides: 18,
  },

  // ────────────────────────────────────────────
  // 🇲🇦 MAROCAINE (~18 plats)
  // ────────────────────────────────────────────
  {
    id: "ma-01",
    cuisine: "ma",
    name: { fr: "Tajine poulet-olives", en: "Chicken & Olive Tagine", es: "Tajín de pollo con aceitunas" },
    calories: 480,
    portion: { fr: "1 portion (350g)", en: "1 serving (350g)", es: "1 porción (350g)" },
    portionGrams: 350,
    proteines: 38, glucides: 22, lipides: 24,
  },
  {
    id: "ma-02",
    cuisine: "ma",
    name: { fr: "Couscous royal (agneau + légumes)", en: "Royal Couscous (lamb + veg)", es: "Cuscús real (cordero + verduras)" },
    calories: 620,
    portion: { fr: "1 assiette (400g)", en: "1 plate (400g)", es: "1 plato (400g)" },
    portionGrams: 400,
    proteines: 35, glucides: 72, lipides: 18,
  },
  {
    id: "ma-03",
    cuisine: "ma",
    name: { fr: "Harira (soupe)", en: "Harira Soup", es: "Sopa Harira" },
    calories: 210,
    portion: { fr: "1 bol (350ml)", en: "1 bowl (350ml)", es: "1 tazón (350ml)" },
    portionGrams: 350,
    proteines: 12, glucides: 28, lipides: 5,
  },
  {
    id: "ma-04",
    cuisine: "ma",
    name: { fr: "Briouates au fromage (x4)", en: "Cheese Briouats (x4)", es: "Briouats de queso (x4)" },
    calories: 320,
    portion: { fr: "4 pièces", en: "4 pieces", es: "4 piezas" },
    portionGrams: 160,
    proteines: 12, glucides: 28, lipides: 16,
  },
  {
    id: "ma-05",
    cuisine: "ma",
    name: { fr: "Pastilla au poulet (part)", en: "Chicken Pastilla (slice)", es: "Pastilla de pollo (porción)" },
    calories: 510,
    portion: { fr: "1 part", en: "1 slice", es: "1 porción" },
    portionGrams: 220,
    proteines: 28, glucides: 42, lipides: 22,
  },
  {
    id: "ma-06",
    cuisine: "ma",
    name: { fr: "Msemen (crêpe feuilletée, x2)", en: "Msemen (layered pancake, x2)", es: "Msemen (crepe hojaldrada, x2)" },
    calories: 380,
    portion: { fr: "2 pièces", en: "2 pieces", es: "2 piezas" },
    portionGrams: 160,
    proteines: 8, glucides: 52, lipides: 14,
  },
  {
    id: "ma-07",
    cuisine: "ma",
    name: { fr: "Mechoui (agneau rôti)", en: "Mechoui (roasted lamb)", es: "Mechoui (cordero asado)" },
    calories: 540,
    portion: { fr: "1 portion (250g)", en: "1 serving (250g)", es: "1 porción (250g)" },
    portionGrams: 250,
    proteines: 48, glucides: 0, lipides: 36,
  },
  {
    id: "ma-08",
    cuisine: "ma",
    name: { fr: "Chebakia (gâteau miel-sésame)", en: "Chebakia (honey-sesame cookie)", es: "Chebakia (galleta de miel y sésamo)" },
    calories: 180,
    portion: { fr: "1 pièce", en: "1 piece", es: "1 pieza" },
    portionGrams: 50,
    proteines: 3, glucides: 22, lipides: 9,
  },
  {
    id: "ma-09",
    cuisine: "ma",
    name: { fr: "Khobz (pain marocain)", en: "Khobz (Moroccan bread)", es: "Khobz (pan marroquí)" },
    calories: 220,
    portion: { fr: "1 petit pain (100g)", en: "1 loaf (100g)", es: "1 pan pequeño (100g)" },
    portionGrams: 100,
    proteines: 7, glucides: 44, lipides: 2,
  },
  {
    id: "ma-10",
    cuisine: "ma",
    name: { fr: "Bissara (soupe de fèves)", en: "Bissara (fava bean soup)", es: "Bissara (sopa de habas)" },
    calories: 180,
    portion: { fr: "1 bol (300ml)", en: "1 bowl (300ml)", es: "1 tazón (300ml)" },
    portionGrams: 300,
    proteines: 10, glucides: 24, lipides: 5,
  },
  {
    id: "ma-11",
    cuisine: "ma",
    name: { fr: "Zaalouk (salade d'aubergines)", en: "Zaalouk (eggplant salad)", es: "Zaalouk (ensalada de berenjena)" },
    calories: 130,
    portion: { fr: "1 portion (150g)", en: "1 serving (150g)", es: "1 porción (150g)" },
    portionGrams: 150,
    proteines: 2, glucides: 12, lipides: 8,
  },
  {
    id: "ma-12",
    cuisine: "ma",
    name: { fr: "Kefta grillée (boulettes, x5)", en: "Grilled Kefta (meatballs, x5)", es: "Kefta a la plancha (albóndigas, x5)" },
    calories: 340,
    portion: { fr: "5 boulettes", en: "5 meatballs", es: "5 albóndigas" },
    portionGrams: 200,
    proteines: 28, glucides: 4, lipides: 22,
  },
  {
    id: "ma-13",
    cuisine: "ma",
    name: { fr: "Sfenj (beignets, x3)", en: "Sfenj (doughnuts, x3)", es: "Sfenj (buñuelos, x3)" },
    calories: 310,
    portion: { fr: "3 sfenj", en: "3 doughnuts", es: "3 buñuelos" },
    portionGrams: 150,
    proteines: 6, glucides: 42, lipides: 13,
  },
  {
    id: "ma-14",
    cuisine: "ma",
    name: { fr: "Sellou (sucrerie aux amandes)", en: "Sellou (almond sweet)", es: "Sellou (dulce de almendras)" },
    calories: 210,
    portion: { fr: "1 portion (60g)", en: "1 serving (60g)", es: "1 porción (60g)" },
    portionGrams: 60,
    proteines: 5, glucides: 22, lipides: 12,
  },
  {
    id: "ma-15",
    cuisine: "ma",
    name: { fr: "Maakouda (galette de pomme de terre, x2)", en: "Maakouda (potato patty, x2)", es: "Maakouda (tortita de patata, x2)" },
    calories: 280,
    portion: { fr: "2 galettes", en: "2 patties", es: "2 tortitas" },
    portionGrams: 180,
    proteines: 6, glucides: 36, lipides: 12,
  },
  {
    id: "ma-16",
    cuisine: "ma",
    name: { fr: "Couscous tfaya (raisins + oignons)", en: "Couscous Tfaya (raisins + onions)", es: "Cuscús tfaya (pasas + cebollas)" },
    calories: 580,
    portion: { fr: "1 assiette (380g)", en: "1 plate (380g)", es: "1 plato (380g)" },
    portionGrams: 380,
    proteines: 22, glucides: 88, lipides: 14,
  },
  {
    id: "ma-17",
    cuisine: "ma",
    name: { fr: "Loubia (haricots blancs en sauce)", en: "Loubia (white bean stew)", es: "Loubia (estofado de judías blancas)" },
    calories: 240,
    portion: { fr: "1 bol (300g)", en: "1 bowl (300g)", es: "1 tazón (300g)" },
    portionGrams: 300,
    proteines: 12, glucides: 36, lipides: 5,
  },
  {
    id: "ma-18",
    cuisine: "ma",
    name: { fr: "Thé à la menthe (avec sucre)", en: "Mint Tea (with sugar)", es: "Té a la menta (con azúcar)" },
    calories: 60,
    portion: { fr: "1 verre (200ml)", en: "1 glass (200ml)", es: "1 vaso (200ml)" },
    portionGrams: 200,
    proteines: 0, glucides: 15, lipides: 0,
  },

  // ────────────────────────────────────────────
  // 🇫🇷 FRANÇAISE (~8 plats)
  // ────────────────────────────────────────────
  {
    id: "fr-01",
    cuisine: "fr",
    name: { fr: "Quiche Lorraine (part)", en: "Quiche Lorraine (slice)", es: "Quiche Lorraine (porción)" },
    calories: 420,
    portion: { fr: "1 part", en: "1 slice", es: "1 porción" },
    portionGrams: 180,
    proteines: 16, glucides: 22, lipides: 28,
  },
  {
    id: "fr-02",
    cuisine: "fr",
    name: { fr: "Croque-monsieur", en: "Croque-Monsieur", es: "Croque-monsieur" },
    calories: 430,
    portion: { fr: "1 sandwich", en: "1 sandwich", es: "1 sándwich" },
    portionGrams: 200,
    proteines: 22, glucides: 35, lipides: 22,
  },
  {
    id: "fr-03",
    cuisine: "fr",
    name: { fr: "Soupe à l'oignon", en: "French Onion Soup", es: "Sopa de cebolla francesa" },
    calories: 280,
    portion: { fr: "1 bol (350ml)", en: "1 bowl (350ml)", es: "1 tazón (350ml)" },
    portionGrams: 350,
    proteines: 12, glucides: 28, lipides: 12,
  },
  {
    id: "fr-04",
    cuisine: "fr",
    name: { fr: "Bœuf Bourguignon", en: "Beef Bourguignon", es: "Buey Borgoña" },
    calories: 490,
    portion: { fr: "1 assiette (300g)", en: "1 plate (300g)", es: "1 plato (300g)" },
    portionGrams: 300,
    proteines: 38, glucides: 18, lipides: 24,
  },
  {
    id: "fr-05",
    cuisine: "fr",
    name: { fr: "Ratatouille", en: "Ratatouille", es: "Ratatouille" },
    calories: 180,
    portion: { fr: "1 assiette (300g)", en: "1 plate (300g)", es: "1 plato (300g)" },
    portionGrams: 300,
    proteines: 4, glucides: 22, lipides: 8,
  },
  {
    id: "fr-06",
    cuisine: "fr",
    name: { fr: "Croissant beurre", en: "Butter Croissant", es: "Croissant de mantequilla" },
    calories: 270,
    portion: { fr: "1 croissant", en: "1 croissant", es: "1 croissant" },
    portionGrams: 80,
    proteines: 5, glucides: 30, lipides: 14,
  },
  {
    id: "fr-07",
    cuisine: "fr",
    name: { fr: "Tarte Tatin (part)", en: "Tarte Tatin (slice)", es: "Tarta Tatin (porción)" },
    calories: 350,
    portion: { fr: "1 part", en: "1 slice", es: "1 porción" },
    portionGrams: 150,
    proteines: 4, glucides: 48, lipides: 16,
  },
  {
    id: "fr-08",
    cuisine: "fr",
    name: { fr: "Crêpe Suzette", en: "Crêpe Suzette", es: "Crêpe Suzette" },
    calories: 290,
    portion: { fr: "2 crêpes", en: "2 crêpes", es: "2 crêpes" },
    portionGrams: 150,
    proteines: 6, glucides: 38, lipides: 12,
  },

  // ────────────────────────────────────────────
  // 🇮🇹 ITALIENNE (~8 plats)
  // ────────────────────────────────────────────
  {
    id: "it-01",
    cuisine: "it",
    name: { fr: "Spaghetti Bolognaise", en: "Spaghetti Bolognese", es: "Espaguetis a la boloñesa" },
    calories: 550,
    portion: { fr: "1 assiette (350g)", en: "1 plate (350g)", es: "1 plato (350g)" },
    portionGrams: 350,
    proteines: 28, glucides: 65, lipides: 16,
  },
  {
    id: "it-02",
    cuisine: "it",
    name: { fr: "Pizza Margherita (2 parts)", en: "Margherita Pizza (2 slices)", es: "Pizza Margarita (2 porciones)" },
    calories: 500,
    portion: { fr: "2 parts", en: "2 slices", es: "2 porciones" },
    portionGrams: 260,
    proteines: 20, glucides: 62, lipides: 16,
  },
  {
    id: "it-03",
    cuisine: "it",
    name: { fr: "Risotto aux champignons", en: "Mushroom Risotto", es: "Risotto de champiñones" },
    calories: 430,
    portion: { fr: "1 assiette (300g)", en: "1 plate (300g)", es: "1 plato (300g)" },
    portionGrams: 300,
    proteines: 10, glucides: 68, lipides: 12,
  },
  {
    id: "it-04",
    cuisine: "it",
    name: { fr: "Lasagnes (part)", en: "Lasagna (serving)", es: "Lasaña (porción)" },
    calories: 490,
    portion: { fr: "1 part", en: "1 serving", es: "1 porción" },
    portionGrams: 280,
    proteines: 24, glucides: 45, lipides: 22,
  },
  {
    id: "it-05",
    cuisine: "it",
    name: { fr: "Tiramisu", en: "Tiramisu", es: "Tiramisú" },
    calories: 370,
    portion: { fr: "1 part (150g)", en: "1 serving (150g)", es: "1 porción (150g)" },
    portionGrams: 150,
    proteines: 7, glucides: 38, lipides: 20,
  },
  {
    id: "it-06",
    cuisine: "it",
    name: { fr: "Bruschetta (x2)", en: "Bruschetta (x2)", es: "Bruschetta (x2)" },
    calories: 220,
    portion: { fr: "2 pièces", en: "2 pieces", es: "2 piezas" },
    portionGrams: 120,
    proteines: 6, glucides: 32, lipides: 7,
  },
  {
    id: "it-07",
    cuisine: "it",
    name: { fr: "Osso Buco", en: "Osso Buco", es: "Osobuco" },
    calories: 520,
    portion: { fr: "1 portion (300g)", en: "1 serving (300g)", es: "1 porción (300g)" },
    portionGrams: 300,
    proteines: 42, glucides: 14, lipides: 28,
  },
  {
    id: "it-08",
    cuisine: "it",
    name: { fr: "Panna Cotta", en: "Panna Cotta", es: "Panna Cotta" },
    calories: 280,
    portion: { fr: "1 verrine (150g)", en: "1 serving (150g)", es: "1 porción (150g)" },
    portionGrams: 150,
    proteines: 4, glucides: 28, lipides: 16,
  },

  // ────────────────────────────────────────────
  // 🇲🇽 MEXICAINE (~8 plats)
  // ────────────────────────────────────────────
  {
    id: "mx-01",
    cuisine: "mx",
    name: { fr: "Tacos al Pastor (x3)", en: "Tacos al Pastor (x3)", es: "Tacos al Pastor (x3)" },
    calories: 480,
    portion: { fr: "3 tacos", en: "3 tacos", es: "3 tacos" },
    portionGrams: 270,
    proteines: 28, glucides: 48, lipides: 16,
  },
  {
    id: "mx-02",
    cuisine: "mx",
    name: { fr: "Burrito au poulet", en: "Chicken Burrito", es: "Burrito de pollo" },
    calories: 550,
    portion: { fr: "1 burrito", en: "1 burrito", es: "1 burrito" },
    portionGrams: 300,
    proteines: 32, glucides: 58, lipides: 18,
  },
  {
    id: "mx-03",
    cuisine: "mx",
    name: { fr: "Guacamole + tortillas chips", en: "Guacamole + Tortilla Chips", es: "Guacamole + totopos" },
    calories: 340,
    portion: { fr: "1 portion (200g)", en: "1 serving (200g)", es: "1 porción (200g)" },
    portionGrams: 200,
    proteines: 4, glucides: 32, lipides: 22,
  },
  {
    id: "mx-04",
    cuisine: "mx",
    name: { fr: "Enchiladas au poulet (x2)", en: "Chicken Enchiladas (x2)", es: "Enchiladas de pollo (x2)" },
    calories: 490,
    portion: { fr: "2 enchiladas", en: "2 enchiladas", es: "2 enchiladas" },
    portionGrams: 280,
    proteines: 30, glucides: 45, lipides: 20,
  },
  {
    id: "mx-05",
    cuisine: "mx",
    name: { fr: "Quesadilla fromage", en: "Cheese Quesadilla", es: "Quesadilla de queso" },
    calories: 400,
    portion: { fr: "1 quesadilla", en: "1 quesadilla", es: "1 quesadilla" },
    portionGrams: 200,
    proteines: 18, glucides: 38, lipides: 20,
  },
  {
    id: "mx-06",
    cuisine: "mx",
    name: { fr: "Tamales (x2)", en: "Tamales (x2)", es: "Tamales (x2)" },
    calories: 420,
    portion: { fr: "2 tamales", en: "2 tamales", es: "2 tamales" },
    portionGrams: 220,
    proteines: 14, glucides: 52, lipides: 16,
  },
  {
    id: "mx-07",
    cuisine: "mx",
    name: { fr: "Pozole (soupe)", en: "Pozole Soup", es: "Pozole" },
    calories: 300,
    portion: { fr: "1 bol (400ml)", en: "1 bowl (400ml)", es: "1 tazón (400ml)" },
    portionGrams: 400,
    proteines: 20, glucides: 35, lipides: 7,
  },
  {
    id: "mx-08",
    cuisine: "mx",
    name: { fr: "Churros (x3)", en: "Churros (x3)", es: "Churros (x3)" },
    calories: 310,
    portion: { fr: "3 churros", en: "3 churros", es: "3 churros" },
    portionGrams: 120,
    proteines: 4, glucides: 42, lipides: 14,
  },

  // ────────────────────────────────────────────
  // 🇯🇵 JAPONAISE (~6 plats)
  // ────────────────────────────────────────────
  {
    id: "jp-01",
    cuisine: "jp",
    name: { fr: "Sushi assortis (8 pièces)", en: "Assorted Sushi (8 pieces)", es: "Sushi variado (8 piezas)" },
    calories: 340,
    portion: { fr: "8 pièces", en: "8 pieces", es: "8 piezas" },
    portionGrams: 240,
    proteines: 18, glucides: 48, lipides: 6,
  },
  {
    id: "jp-02",
    cuisine: "jp",
    name: { fr: "Ramen au poulet", en: "Chicken Ramen", es: "Ramen de pollo" },
    calories: 490,
    portion: { fr: "1 bol (400ml)", en: "1 bowl (400ml)", es: "1 tazón (400ml)" },
    portionGrams: 400,
    proteines: 26, glucides: 62, lipides: 12,
  },
  {
    id: "jp-03",
    cuisine: "jp",
    name: { fr: "Gyozas frits (x6)", en: "Pan-Fried Gyoza (x6)", es: "Gyoza fritos (x6)" },
    calories: 330,
    portion: { fr: "6 pièces", en: "6 pieces", es: "6 piezas" },
    portionGrams: 180,
    proteines: 14, glucides: 32, lipides: 16,
  },
  {
    id: "jp-04",
    cuisine: "jp",
    name: { fr: "Tempura de crevettes (x5)", en: "Shrimp Tempura (x5)", es: "Tempura de gambas (x5)" },
    calories: 380,
    portion: { fr: "5 pièces", en: "5 pieces", es: "5 piezas" },
    portionGrams: 200,
    proteines: 18, glucides: 35, lipides: 18,
  },
  {
    id: "jp-05",
    cuisine: "jp",
    name: { fr: "Onigiri (x2)", en: "Onigiri (x2)", es: "Onigiri (x2)" },
    calories: 280,
    portion: { fr: "2 onigiri", en: "2 onigiri", es: "2 onigiri" },
    portionGrams: 200,
    proteines: 6, glucides: 56, lipides: 2,
  },
  {
    id: "jp-06",
    cuisine: "jp",
    name: { fr: "Miso Soupe + riz blanc", en: "Miso Soup + Steamed Rice", es: "Sopa miso + arroz blanco" },
    calories: 290,
    portion: { fr: "1 bol soupe + 150g riz", en: "1 bowl soup + 150g rice", es: "1 tazón sopa + 150g arroz" },
    portionGrams: 350,
    proteines: 8, glucides: 52, lipides: 4,
  },
];

// ────────────────────────────────────────────
// HELPERS
// ────────────────────────────────────────────

export type Lang = "fr" | "en" | "es";

export function searchLocalFoods(query: string, lang: Lang): LocalFood[] {
  if (!query || query.trim().length < 2) return [];
  const normalize = (s: string) =>
    s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  const q = normalize(query.trim());
  return foodDatabase.filter((food) => normalize(food.name[lang]).includes(q));
}

export function getFoodsByCuisine(cuisine: LocalFood["cuisine"]): LocalFood[] {
  return foodDatabase.filter((f) => f.cuisine === cuisine);
}

export const cuisineFlags: Record<LocalFood["cuisine"], string> = {
  daily: "⭐",
  us: "🇺🇸",
  ca: "🇨🇦",
  ma: "🇲🇦",
  fr: "🇫🇷",
  it: "🇮🇹",
  mx: "🇲🇽",
  jp: "🇯🇵",
};

export const cuisineLabels: Record<LocalFood["cuisine"], Record<Lang, string>> = {
  daily: { fr: "Quotidien", en: "Everyday", es: "Cotidiano" },
  us: { fr: "Américaine", en: "American", es: "Americana" },
  ca: { fr: "Canadienne", en: "Canadian", es: "Canadiense" },
  ma: { fr: "Marocaine", en: "Moroccan", es: "Marroquí" },
  fr: { fr: "Française", en: "French", es: "Francesa" },
  it: { fr: "Italienne", en: "Italian", es: "Italiana" },
  mx: { fr: "Mexicaine", en: "Mexican", es: "Mexicana" },
  jp: { fr: "Japonaise", en: "Japanese", es: "Japonesa" },
};
